name: Docker Image CI
 
on:

  push:

    branches: [ main ]

  pull_request:

    branches: [ main ]

permissions:

    id-token: write

    contents: read

env:

  BUILD_CONTEXT: .

  ACR_NAME: Quantumregisztery

  ACR_RG: quantum
 
jobs:
 
  build:
 
    runs-on: ubuntu-latest
 
    steps:

    - name: Azure Login

      uses: azure/login@v1

      with:

        creds: '{"clientId":"${{ secrets.Azure_client_id }}","subscriptionId":"${{ secrets.Azure_subscription_id }}","tenantId":"${{ secrets.Azure_tenant_id }}"}'
